//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int IdStudent { get; set; }
        public string Fam { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<int> IdGr { get; set; }
        public Nullable<System.DateTime> DR { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual Gruppa Gruppa { get; set; }
    }
}
